---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4
        ports:
        - containerPort: 6379
---
kind: Service
apiVersion: v1
metadata:
  name: redis-service
  namespace: prometheus
spec:
  selector:
    app: redis
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
