---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  labels:
    name: redis-exporter
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      name: redis-exporter
      labels:
        app: redis-exporter
      annotations:
         prometheus.io/scrape: "true"
         prometheus.io/port: "9121"
         metrics.dynatrace.com/scrape: "true"
         metric.dynatrace.com/filter: |
        {
          "mode": "include",
          "names": [
              "redis_uptime_in_seconds",
              "redis_connected_clients"
              ]
        }
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        ports:
        - containerPort: 9121
---
kind: Service
apiVersion: v1
metadata:
  name: redis-exporter
  namespace: prometheus
spec:
  selector:
    app: redis-exporter
  ports:
  - name: redis-exporter
    protocol: TCP
    port: 9121
    targetPort: 9121
